<a href="https://colab.research.google.com/github/corrine1106/git_practice/blob/master/W1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Z-score

In [3]:
import numpy as np
from scipy import stats

In [4]:
data = np.array([200,300,400,600,1000])

In [5]:
zscore = stats.zscore(data)

In [6]:
zscore

array([-1.06066017, -0.70710678, -0.35355339,  0.35355339,  1.76776695])

In [21]:
import sklearn.preprocessing as preprocess

In [22]:
preprocess.scale(data.reshape(-1,1))

array([[-1.06066017],
       [-0.70710678],
       [-0.35355339],
       [ 0.35355339],
       [ 1.76776695]])

In [23]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [24]:
scale.fit_transform(data.reshape(-1,1))

array([[-1.06066017],
       [-0.70710678],
       [-0.35355339],
       [ 0.35355339],
       [ 1.76776695]])

## Min-Max

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
scaler = MinMaxScaler()

In [10]:
scaler.fit_transform(data.reshape(-1, 1))

array([[0.   ],
       [0.125],
       [0.25 ],
       [0.5  ],
       [1.   ]])